# Generated by Django 5.0.2 on 2025-05-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_store_categ_name_1278fd_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/no-image.png', upload_to='products/%Y/%m/%d'),
        ),
    ]
